### ISSUE TITLE
Session web links aren't be mapped to session id

### ISSUE THREAD

**Issue by amlcurran** [droidcon/iosched#36] opened 2013-09-19 11:43 UTC
The website uses links for each session such as "/sessions/session-title-here". Trying to implement opening sessions but the fragment requires a sessionId, which can't be retrieved from the link.

**Comment by rock3r** [comment] 2013-09-19 12:14
Duplicate of #18

**Comment by alsutton** [comment] 2013-09-19 12:32
It's slightly different. This is about allowing us to map a session to a URL, #18 is about making sure the mapping works and sends us to the right place.

**Comment by rock3r** [comment] 2013-09-19 12:44
Yes, you're right.

**Closed as completed** 2013-09-19 13:34 UTC
